import { Task, WorkSession } from '../types';

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: '機械学習の論文を読む',
    description: 'Attention Is All You Need を精読してノートにまとめる',
    priority: 'high',
    status: 'in_progress',
    deadline: '2026-06-05',
    category: '研究',
    estimatedMinutes: 180,
    actualMinutes: 90,
    createdAt: '2026-05-20',
  },
  {
    id: 't2',
    title: '実験コードのリファクタリング',
    description: 'データ前処理パイプラインを整理する',
    priority: 'medium',
    status: 'pending',
    deadline: '2026-06-10',
    category: '研究',
    estimatedMinutes: 120,
    actualMinutes: 0,
    createdAt: '2026-05-22',
  },
  {
    id: 't3',
    title: '統計学の演習問題（第5章）',
    description: '確率分布と仮説検定の演習',
    priority: 'high',
    status: 'pending',
    deadline: '2026-06-03',
    category: '勉強',
    estimatedMinutes: 90,
    actualMinutes: 0,
    createdAt: '2026-05-23',
  },
  {
    id: 't4',
    title: '研究進捗報告のスライド作成',
    description: '6月の中間発表に向けたスライド準備',
    priority: 'high',
    status: 'pending',
    deadline: '2026-06-08',
    category: '研究',
    estimatedMinutes: 240,
    actualMinutes: 0,
    createdAt: '2026-05-24',
  },
  {
    id: 't5',
    title: 'Python 深層学習フレームワーク学習',
    description: 'PyTorch チュートリアルの完了',
    priority: 'medium',
    status: 'in_progress',
    deadline: '2026-06-15',
    category: '勉強',
    estimatedMinutes: 300,
    actualMinutes: 120,
    createdAt: '2026-05-18',
  },
  {
    id: 't6',
    title: '英語論文の要約作成',
    description: '関連研究3本の要約をまとめる',
    priority: 'low',
    status: 'pending',
    deadline: '2026-06-20',
    category: '研究',
    estimatedMinutes: 150,
    actualMinutes: 0,
    createdAt: '2026-05-25',
  },
  {
    id: 't7',
    title: '線形代数の復習',
    description: '行列演算・固有値分解の確認',
    priority: 'low',
    status: 'completed',
    deadline: '2026-05-28',
    category: '勉強',
    estimatedMinutes: 60,
    actualMinutes: 75,
    createdAt: '2026-05-15',
  },
];

const today = '2026-05-30';
const yesterday = '2026-05-29';
const twoDaysAgo = '2026-05-28';
const threeDaysAgo = '2026-05-27';
const fourDaysAgo = '2026-05-26';
const fiveDaysAgo = '2026-05-25';
const sixDaysAgo = '2026-05-24';

export const mockSessions: WorkSession[] = [
  {
    id: 's1',
    taskId: 't1',
    taskTitle: '機械学習の論文を読む',
    category: '研究',
    startTime: `${today}T09:00:00`,
    endTime: `${today}T10:30:00`,
    durationMinutes: 90,
    content: 'Transformer アーキテクチャの Self-Attention 機構について精読。図2のMulti-Head Attentionの仕組みをノートにまとめた。',
    insights: 'Positional Encoding の必要性が以前より明確に理解できた。',
    nextAction: 'Section 4（Why Self-Attention）を読む',
    date: today,
  },
  {
    id: 's2',
    taskId: 't5',
    taskTitle: 'PyTorch チュートリアル',
    category: '勉強',
    startTime: `${today}T11:00:00`,
    endTime: `${today}T12:00:00`,
    durationMinutes: 60,
    content: 'DataLoader と Dataset クラスの使い方を学習。カスタムデータセットの実装を試した。',
    insights: 'transform の使い方で詰まっていた部分が解決できた。',
    nextAction: 'モデルの学習ループを実装する',
    date: today,
  },
  {
    id: 's3',
    taskId: 't3',
    taskTitle: '統計学 第5章演習',
    category: '勉強',
    startTime: `${yesterday}T14:00:00`,
    endTime: `${yesterday}T15:30:00`,
    durationMinutes: 90,
    content: '正規分布と t 検定の演習問題を10問解いた。',
    insights: '第一種過誤と第二種過誤の違いがようやく整理できた。',
    nextAction: '演習問題の後半10問を解く',
    date: yesterday,
  },
  {
    id: 's4',
    taskId: 't1',
    taskTitle: '機械学習の論文を読む',
    category: '研究',
    startTime: `${yesterday}T09:30:00`,
    endTime: `${yesterday}T11:00:00`,
    durationMinutes: 90,
    content: 'Encoder-Decoder 構造の詳細を読み進めた。Residual Connection の意義について考察。',
    insights: '層正規化の順序（Pre-LN vs Post-LN）が重要なことを発見。',
    nextAction: 'アブレーション実験の節を読む',
    date: yesterday,
  },
  {
    id: 's5',
    taskId: 't5',
    taskTitle: 'PyTorch チュートリアル',
    category: '勉強',
    startTime: `${twoDaysAgo}T10:00:00`,
    endTime: `${twoDaysAgo}T12:00:00`,
    durationMinutes: 120,
    content: 'CNN の基本実装を完成させた。CIFAR-10 で 65% の精度を達成。',
    insights: 'バッチサイズとエポック数のバランスが大事と実感。',
    nextAction: 'RNN・LSTM の実装に進む',
    date: twoDaysAgo,
  },
  {
    id: 's6',
    taskId: 't4',
    taskTitle: '研究進捗報告スライド作成',
    category: '研究',
    startTime: `${twoDaysAgo}T14:00:00`,
    endTime: `${twoDaysAgo}T15:30:00`,
    durationMinutes: 90,
    content: 'スライドの全体構成を決定。研究背景と問題設定のスライドを5枚作成。',
    insights: '先行研究の整理が不十分なことに気づいた。',
    nextAction: '関連研究の節を先に充実させる',
    date: twoDaysAgo,
  },
  {
    id: 's7',
    taskId: 't7',
    taskTitle: '線形代数の復習',
    category: '勉強',
    startTime: `${threeDaysAgo}T09:00:00`,
    endTime: `${threeDaysAgo}T10:15:00`,
    durationMinutes: 75,
    content: '固有値分解と特異値分解を復習。PCA との関係を整理した。',
    insights: 'SVD が次元削減の理論的根拠になっていることが改めて理解できた。',
    nextAction: '完了',
    date: threeDaysAgo,
  },
  {
    id: 's8',
    taskId: 't1',
    taskTitle: '機械学習の論文を読む',
    category: '研究',
    startTime: `${fourDaysAgo}T13:00:00`,
    endTime: `${fourDaysAgo}T14:30:00`,
    durationMinutes: 90,
    content: 'Introduction と Related Work を精読。引用論文リストを作成した。',
    insights: 'Seq2Seq モデルとの比較がポイントになる。',
    nextAction: 'Architecture の節を読む',
    date: fourDaysAgo,
  },
  {
    id: 's9',
    taskId: 't5',
    taskTitle: 'PyTorch チュートリアル',
    category: '勉強',
    startTime: `${fiveDaysAgo}T10:00:00`,
    endTime: `${fiveDaysAgo}T11:30:00`,
    durationMinutes: 90,
    content: 'テンソル操作の基礎、自動微分（Autograd）の仕組みを学習。',
    insights: '計算グラフの概念が PyTorch の動的グラフで理解しやすかった。',
    nextAction: 'NN モジュールの使い方を学ぶ',
    date: fiveDaysAgo,
  },
  {
    id: 's10',
    taskId: 't3',
    taskTitle: '統計学 第5章演習',
    category: '勉強',
    startTime: `${sixDaysAgo}T15:00:00`,
    endTime: `${sixDaysAgo}T16:00:00`,
    durationMinutes: 60,
    content: '仮説検定の基礎概念を復習。p値の解釈を再確認した。',
    insights: 'p値は帰無仮説のもとでのデータの珍しさを表すという解釈が腑に落ちた。',
    nextAction: '実際の演習問題を解き始める',
    date: sixDaysAgo,
  },
];

export const CATEGORIES = ['研究', '勉強', '読書', 'コーディング', 'その他'];

export const CATEGORY_COLORS: Record<string, string> = {
  研究: '#3b82f6',
  勉強: '#10b981',
  読書: '#f59e0b',
  コーディング: '#8b5cf6',
  その他: '#6b7280',
};
